AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GameAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"

  GameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        SaveScore:
          Type: Api
          Properties:
            RestApiId: !Ref GameAPI
            Path: /score
            Method: post
        GetLeaderboard:
          Type: Api
          Properties:
            RestApiId: !Ref GameAPI
            Path: /leaderboard
            Method: get

  GameScoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GameScores
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: score
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ScoreIndex
          KeySchema:
            - AttributeName: score
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          BillingMode: PAY_PER_REQUEST
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${GameAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/"